game_management/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
#from game_management.views.tg_bot import bot_run

#bot_run()
app_name = 'game_management'

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/login/', auth_views.LoginView.as_view()),
    path('accounts/logout/', auth_views.LogoutView.as_view()),
    path('accounts/logout-then-login/', auth_views.logout_then_login),

    path('schedule', views.schedule, name='schedule'),
    path('schedule/schedule_update', views.schedule_update, name='schedule_update'),

    path('members', views.members, name='members'),
    path('masters', views.masters, name='masters'),
    path('game_registered', views.game_registered, name='game_registered'),

    path('results', views.results, name='results'),
    path('rating', views.rating, name='rating'),

    path('promo', views.promo, name='promo'),
    path('promo/update_promo', views.update_promo, name='update_promo'),
    path('promo/delete_promo', views.delete_promo, name='delete_promo'),

    path('glossary', views.glossary, name='glossary'),
    path('bot', views.bot, name='bot'),

    path('glossary/games', views.games, name='games'),
    path('glossary/games/update_game', views.update_game, name='update_game'),
    path('glossary/games/delete_game', views.delete_game, name='delete_game'),

    path('glossary/game_result', views.game_result, name='game_result'),
    path('glossary/game_result/update_result', views.update_result, name='update_result'),
    path('glossary/game_result/delete_result', views.delete_result, name='delete_result'),

    path('glossary/role', views.role, name='role'),
    path('glossary/role/update_role', views.update_role, name='update_role'),
    path('glossary/role/delete_role', views.delete_role, name='delete_role'),

    path('glossary/member_result', views.member_result, name='member_result'),
    path('glossary/member_result/update_member_result', views.update_member_result, name='update_member_result'),
    path('glossary/member_result/delete_member_result', views.delete_member_result, name='delete_member_result'),

    path('glossary/game_functions', views.game_functions, name='game_functions'),
    path('glossary/game_functions/update_function', views.update_function, name='update_function'),
    path('glossary/game_functions/delete_function', views.delete_function, name='delete_function'),

    path('location', views.location, name='location'),
    path('location/update_location', views.update_location, name='update_location'),
    path('location/delete_location', views.delete_location, name='delete_location'),
]

upsystems_bot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game_management/', include('game_management.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

game_management/views/bot.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth.decorators import login_required, permission_required
from game_management.views import tg_bot


@login_required()
def bot(request):
    context = {}
    return render(request, 'game_management/bot.html', context)

game_management/views/game_registered.py
import datetime
from datetime import timedelta

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from game_management.models import Member, RegisteredToGame, Schedule


@login_required()
def game_registered(request):
    today = datetime.date.today()
    schedule = Schedule.objects.filter(date__gte=today, date__lte=today + timedelta(days=6)).order_by('-date')
    registered_to_game = []
    for day in schedule:
        game = RegisteredToGame.objects.filter(schedule=day, active=True)
        number_registered = game.count()
        members = game.values_list('member__nickname', flat=True)
        registered_to_game.append([day, number_registered, members])
    context = {'registered_to_game': registered_to_game}
    return render(request, 'game_management/game_registered.html', context)

game_management/views/glossary.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth.decorators import login_required
from game_management.models import GameType, GameResult, Role, MemberResult, GameFunction, Location
from django.contrib.auth.models import User


@login_required()
def glossary(request):
    games = GameType.objects.filter(active=True).count()
    game_results = GameResult.objects.filter(active=True).count()
    roles = Role.objects.filter(active=True).count()
    member_results = MemberResult.objects.filter(active=True).count()
    game_functions = GameFunction.objects.filter(active=True).count()
    context = {'games': games, 'game_results': game_results, 'roles': roles, 'member_results': member_results,
               'game_functions': game_functions}
    return render(request, 'game_management/glossary.html', context)


@login_required()
def games(request):
    games = GameType.objects.filter(active=True)
    context = {'games': games}
    return render(request, 'game_management/glossary/games.html', context)


def update_game(request):
    name = request.POST['name']
    description = request.POST['description']
    try:
        game_id = request.POST['game_id']
        game = GameType.objects.get(id=game_id)
        game.game_name = name
    except:
        game = GameType(game_name=name)
    game.game_description = description
    game.save()
    return HttpResponseRedirect(reverse('game_management:games'))


def delete_game(request):
    try:
        game = GameType.objects.get(id=request.POST['to_delete'])
        game.active = False
        game.save()
    except:
        pass
    return HttpResponseRedirect(reverse('game_management:games'))


@login_required()
def game_result(request):
    results = GameResult.objects.filter(active=True)
    game_types = GameType.objects.all()
    context = {'results': results, 'game_types': game_types}
    return render(request, 'game_management/glossary/game_result.html', context)


def update_result(request):
    name = request.POST['result']
    game = GameType.objects.get(id=request.POST['game'])
    try:
        result_id = request.POST['result_id']
        result = GameResult.objects.get(id=result_id)
        result.game_result = name
    except:
        result = GameResult(game_result=name)
    result.game_type = game
    result.save()
    return HttpResponseRedirect(reverse('game_management:game_result'))


def delete_result(request):
    try:
        result = GameResult.objects.get(id=request.POST['to_delete'])
        result.active = False
        result.save()
    except:
        pass
    return HttpResponseRedirect(reverse('game_management:game_result'))

@login_required()
def role(request):
    roles = Role.objects.filter(active=True)
    game_types = GameType.objects.filter(active=True)
    context = {'roles': roles, 'game_types': game_types}
    return render(request, 'game_management/glossary/role.html', context)


def update_role(request):
    role_name = request.POST['role']
    description = request.POST['description']
    side = request.POST['side']
    game = GameType.objects.get(id=request.POST['game'])
    try:
        role_id = request.POST['role_id']
        role = Role.objects.get(id=role_id)
        role.role = role_name
    except:
        role = Role(role=role_name)
    role.role_description = description
    role.side = side
    role.game = game
    role.save()
    return HttpResponseRedirect(reverse('game_management:role'))


def delete_role(request):
    try:
        role = Role.objects.get(id=request.POST['to_delete'])
        role.active = False
        role.save()
    except:
        pass
    return HttpResponseRedirect(reverse('game_management:role'))


@login_required()
def member_result(request):
    results = MemberResult.objects.filter(active=True)
    context = {'results': results}
    return render(request, 'game_management/glossary/member_result.html', context)


def update_member_result(request):
    result = request.POST['name']
    result_type = request.POST['description']
    try:
        result_id = request.POST['game_id']
        member_result = MemberResult.objects.get(id=result_id)
        member_result.member_result = result
    except:
        member_result = MemberResult(member_result=result)
    member_result.member_result_type = result_type
    member_result.save()
    return HttpResponseRedirect(reverse('game_management:member_result'))


def delete_member_result(request):
    try:
        member_result = MemberResult.objects.get(id=request.POST['to_delete'])
        member_result.active = False
        member_result.save()
    except:
        pass
    return HttpResponseRedirect(reverse('game_management:member_result'))

@login_required()
def game_functions(request):
    game_function = GameFunction.objects.filter(active=True)
    context = {'game_function': game_function}
    return render(request, 'game_management/glossary/game_functions.html', context)


def update_function(request):
    name = request.POST['name']
    description = request.POST['description']
    try:
        game_id = request.POST['game_id']
        function = GameFunction.objects.get(id=game_id)
        function.game_function = name
    except:
        function = GameFunction(game_function=name)
    function.game_function_description = description
    function.save()
    return HttpResponseRedirect(reverse('game_management:game_functions'))


def delete_function(request):
    try:
        game = GameFunction.objects.get(id=request.POST['to_delete'])
        game.active = False
        game.save()
    except:
        pass
    return HttpResponseRedirect(reverse('game_management:game_functions'))


@login_required()
def location(request):
    locations = Location.objects.filter(active=True)
    user = User
    context = {'locations': locations, 'user': user}
    return render(request, 'game_management/glossary/location.html', context)

def update_location(request):
    loc_name = request.POST['name']
    loc_address = request.POST['address']
    loc_direction = request.POST['direction']
    loc_point = request.POST['point']
    try:
        loc_scheme = request.FILES['scheme']
    except:
        loc_scheme = None
    try:
        loc_photo = request.FILES['photo']
    except:
        loc_photo = None
    try:
        loc_id = request.POST['loc_id']
        loc = Location.objects.get(id=loc_id)
        loc.location_name = loc_name
    except:
        loc = Location(location_name=loc_name)
    loc.location_address = loc_address
    loc.location_directions = loc_direction
    loc.location_point = loc_point
    loc.location_photo = loc_photo
    loc.direction_photo = loc_scheme
    loc.save()
    return HttpResponseRedirect(reverse('game_management:location'))


def delete_location(request):
    try:
        location = Location.objects.get(id=request.POST['to_delete'])
        location.active = False
        location.save()
    except:
        pass
    return HttpResponseRedirect(reverse('game_management:location'))

game_management/views/location.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth.decorators import login_required
from game_management.models import GameType, GameResult, Role, MemberResult, GameFunction, Location
from django.contrib.auth.models import User

def location(request):
    locations = Location.objects.filter(active=True)
    context = {'locations': locations}
    return render(request, 'game_management/location.html', context)

def update_location(request):
    loc_name = request.POST['name']
    loc_address = request.POST['address']
    loc_direction = request.POST['direction']
    loc_point = request.POST['point']
    try:
        loc_scheme = request.FILES['scheme']
    except:
        loc_scheme = None
    try:
        loc_photo = request.FILES['photo']
    except:
        loc_photo = None
    try:
        loc_id = request.POST['loc_id']
        loc = Location.objects.get(id=loc_id)
        loc.location_name = loc_name
    except:
        loc = Location(location_name=loc_name)
    loc.location_address = loc_address
    loc.location_directions = loc_direction
    loc.location_point = loc_point
    loc.location_photo = loc_photo
    loc.direction_photo = loc_scheme
    loc.save()
    return HttpResponseRedirect(reverse('game_management:location'))


def delete_location(request):
    try:
        location = Location.objects.get(id=request.POST['to_delete'])
        location.active = False
        location.save()
    except:
        pass
    return HttpResponseRedirect(reverse('game_management:location'))

game_management/views/masters.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required


@login_required()
def masters(request):
    context = {}
    return render(request, 'game_management/masters.html', context)

game_management/views/members.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from game_management.models import Member


@login_required()
def members(request):
    members = Member.objects.all().order_by('registered_date')
    context = {'members': members}
    return render(request, 'game_management/members.html', context)

game_management/views/promo.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth.decorators import login_required, permission_required
from game_management.models import Promo


@login_required()
def promo(request):
    promo = Promo.objects.filter(active=True).order_by('-promo_date')
    context = {'promo': promo}
    return render(request, 'game_management/promo.html', context)


def update_promo(request):
    date = request.POST['date']
    par1 = request.POST['par1']
    text1 = request.POST['text1']
    par2 = request.POST['par2']
    text2 = request.POST['text2']
    par3 = request.POST['par3']
    text3 = request.POST['text3']
    par4 = request.POST['par4']
    text4 = request.POST['text4']
    promo_type = request.POST['promo_type']
    try:
        promo_id = request.POST['promo_id']
        promo = Promo.objects.get(id=promo_id)
        promo.promo_date = date
    except:
        promo = Promo(promo_date=date)
    promo.par1 = par1
    promo.text1 = text1
    promo.par2 = par2
    promo.text2 = text2
    promo.par3 = par3
    promo.text3 = text3
    promo.par4 = par4
    promo.text4 = text4
    promo.promo_type = promo_type
    promo.save()
    return HttpResponseRedirect(reverse('game_management:promo'))

def delete_promo(request):
    promo_id = request.POST['pr_id']
    promo = Promo.objects.get(id=promo_id)
    promo.active = False
    promo.save()
    return HttpResponseRedirect(reverse('game_management:promo'))

game_management/views/rating.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required


def rating(request):
    context = {}
    return render(request, 'game_management/rating.html', context)

game_management/views/results.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required


def results(request):
    context = {}
    return render(request, 'game_management/results.html', context)

game_management/views/schedule.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth.decorators import login_required
from game_management.models import Schedule, Location, GameType
import datetime
from datetime import date, timedelta
from django.core.paginator import Paginator


@login_required()
def schedule(request):
    date_now = datetime.date.today()
    schedule_cur = Schedule.objects.filter(active=True).order_by('-date', 'schedule_time_begin')
    games = GameType.objects.filter(active=True).order_by('game_name')
    location = Location.objects.filter(active=True).order_by('location_name')
    date_start = date.today() - timedelta(days=date.today().weekday())
    schedule_dic = {}
    schedule_last = {}
    for sch in schedule_cur:
        if sch.date >= date_start:
            if sch.date not in schedule_last:
                schedule_last[sch.date] = []
            schedule_last[sch.date].append(sch)
        else:
            if sch.date not in schedule_dic:
                schedule_dic[sch.date] = []
            schedule_dic[sch.date].append(sch)

    paginator = Paginator(list(schedule_dic.items()), 21)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    schedule = dict(page_obj.object_list)

    context = {'schedule_last': schedule_last, 'date_start': date_start, 'page_obj': page_obj, 'games': games,
               'location': location, 'schedule': schedule, 'date_now': date_now}
    return render(request, 'game_management/schedule.html', context)


def schedule_update(request):
    date = request.POST['date']
    begin = request.POST['time_begin']
    end = request.POST['time_end']
    loc_id = request.POST['location']
    game_id = request.POST['game']
    location = Location.objects.get(id=loc_id)
    game = GameType.objects.get(id=game_id)
    try:
        sch_id = request.POST['sch_id']
        schedule = Schedule.objects.get(id=sch_id)
        schedule.date = date
    except:
        schedule = Schedule(date=date)
    schedule.schedule_time_begin = begin
    schedule.schedule_time_end = end
    schedule.location = location
    schedule.game = game
    schedule.save()
    return HttpResponseRedirect(reverse('game_management:schedule'))

game_management/templates/game_management/bot.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bot</title>

<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
<!-- MDB -->
<!--<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.css" rel="stylesheet"/><--->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
<!-- Bootstrap core CSS -->
<link href="{% static 'game_management/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">

<link href="{% static 'game_management/style.css' %}" rel="stylesheet" crossorigin="anonymous">
</head>
<body id="bg" style="background-image: url('{% static "img/back2.png"%}');">
{%  include  'game_management/main.html' %}
<br><br>
{{ status }}

<script src="{% static 'game_management/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'game_management/game_management.js' %}" crossorigin="anonymous"></script>

</body>
</html>

game_management/templates/game_management/index.html
<!DOCTYPE html>
{%  load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
<link href="{% static 'game_management/style.css' %}" rel="stylesheet" crossorigin="anonymous">
</head>
<body id="bg" style="background-image: url('{% static "img/back2.png"%}');">
{%  include  'game_management/main.html' %}
<br><br><br><br><br><br>
<div class="row m-2">
    <div class="col-2 text-end">
        {{ promo.par1 }}
    </div>
    <div class="col-8">
        {{ promo.text1 }}
    </div>
</div>
<br>
<div class="row m-2 text-end">
    <div class="col-2">
        {{ promo.par2 }}
    </div>
    <div class="col-8">
        {{ promo.text2 }}
    </div>
</div>
<br>
<div class="row m-2 text-end">
    <div class="col-2">
        {{ promo.par3 }}
    </div>
    <div class="col-8">
        {{ promo.text3 }}
    </div>
</div>
<br>
<div class="row m-2 text-end">
    <div class="col-2">
        {{ promo.par4 }}
    </div>
    <div class="col-8">
        {{ promo.text4 }}
    </div>
</div>
<br>


<br><br>

</body>
</html>

game_management/templates/game_management/location.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Локация</title>
<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
<!-- MDB -->
<!--<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.css" rel="stylesheet"/><--->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
<!-- Bootstrap core CSS -->
<link href="{% static 'game_management/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
<link href="{% static 'game_management/style.css' %}" rel="stylesheet" crossorigin="anonymous">
</head>
<body id="bg" style="background-image: url('{% static "img/back2.png"%}');">
{%  include  'game_management/main.html' %}
<div class="text-end m-2" style="width: 1400px;" >
<!-- Button trigger modal -->
{% if request.user.is_authenticated %}
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#locModal">
Добавить локацию</button>

<!-- Modal -->
<div class="modal fade" id="locModal" tabindex="-1" aria-labelledby="locModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="locModalLabel"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action="{% url 'game_management:update_location' %}" method="post" enctype="multipart/form-data">
      {%  csrf_token %}
      <div class="modal-body">
        <input type="number" class="form-control" name="loc_id" id="loc_id" readonly>
        <input type="text" class="form-control mt-1 mb-1" id="name" name="name" placeholder="название">
        <input type="text" class="form-control mt-1 mb-1" id="address" name="address" placeholder="адрес">
        <label for="direction" class="ms-1 mt-1 mb-1">как проехать</label>
        <textarea type="text" class="form-control mt-1 mb-1" id="direction" name="direction" placeholder="как проехать">
        </textarea>
        <input type="text" class="form-control mt-1 mb-1" id="point" name="point" placeholder="google point">
        <div class="row">
        <div class="col">
        <label for="photo_form" class="mt-1 mb-1">фото</label>
        <input type="file" class="form-control mt-1 mb-1" name="photo" placeholder="фото" accept=".jpg" id="photo_form">
        </div>
        <div class="col">
        <label for="scheme_form" class="mt-1 mb-1" id="scheme">схема</label>
        <input type="file" class="form-control mt-1 mb-1" name="scheme" placeholder="схема проезда" id="scheme_form"
               accept=".jpg" >
        </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"
                onclick="cleaLocationModal();">Отменить</button>
        <button type="submit" class="btn btn-primary">Сохранить</button>
      </div>
      </form>
    </div>
  </div>
</div>

{% else %}
    <br><br>
{% endif %}
</div>



<table class="table table-hover ms-2" style="max-width: 1800px;">
    <thead>
    <tr class="bg-primary bg-opacity-25">
        <th>Название</th>
        <th>Адрес</th>
        <th>Как проехать</th>
        <th>Координата</th>
        <th>Фото</th>
        <th>Схема проезда</th>
        {% if request.user.is_authenticated %}<th></th>{% endif %}
    </tr>
    </thead>
    <tbody>
    {% for loc in locations %}
    <tr class="align-middle bg-opacity-50 bg-light">
        <td>{{ loc.location_name }}</td>
        <td>{{ loc.location_address }}</td>
        <td>{{ loc.location_directions }}</td>
        <td>{{ loc.location_point }}</td>
        <td><img src="{%  get_static_prefix %}locations/{{ loc.location_photo}}" style="max-width: 180px; max-height: 180px;"></td>
        <td><img src="{%  get_static_prefix %}directions/{{ loc.direction_photo }}" style="max-width: 180px; max-height: 180px;"></td>
        {% if request.user.is_authenticated %}
        <td style="width: 170px;">
            <button class="btn btn-outline-primary m-1" type="button" data-bs-toggle="modal" data-bs-target="#locModal"
                    onclick="fillLocationModal(this);" data-id="{{ loc.id }}" data-name="{{ loc.location_name }}"
                    data-address="{{ loc.location_address }}" data-directions="{{ loc.location_directions }}"
                    data-point="{{ loc.location_point }}" data-photo="{{ loc.location_photo.name }}"
                    data-scheme="{{ loc.direction_photo.name }}" style="width: 160px;">
                    <i class="bi bi-pencil-square"></i>&nbsp;Редактировать
            </button>
            <form action="{% url 'game_management:delete_location' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-outline-danger m-1" type="submit" style="width: 160px;">
               <i class="bi bi-x-lg"></i>&nbsp;Удалить
            </button>
            </form>
        </td>
        {% endif %}
    </tr>
    {% endfor %}
    </tbody>
</table>


<script src="{% static 'game_management/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'game_management/game_management.js' %}" crossorigin="anonymous"></script>

</body>
</html>

game_management/templates/game_management/main.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
<!-- MDB -->
<!--<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.css" rel="stylesheet"/><--->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
<!-- Bootstrap core CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<link href="{% static 'game_management/style.css' %}" rel="stylesheet" crossorigin="anonymous">



</head>
<body>
<div class="row justify-content-end">
<div class="col-auto" id="content">
    {% block content %}
    {% endblock %}
</div></div>

<div class="fixed-top" style="width: 80mm;">
<div class="p-2 -m-2" >
<button class="btn btn-outline-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions2" aria-controls="offcanvasWithBothOptions2">
  <i class="fas fa-bars"></i>
    {% if request.user.is_authenticated %}&nbsp {{user.first_name}} {{user.last_name}}{% else %}&nbsp;Гость{% endif %}
</button>
</div>
</div>
<div class="offcanvas offcanvas-start" data-bs-scroll="true"
     tabindex="-1" id="offcanvasWithBothOptions2" aria-labelledby="offcanvasWithBothOptions2Label" style="width:60mm;">
<div class="offcanvas-header">

<!--<h5 class="offcanvas-title" id="offcanvasWithBothOptions2Label">&nbsp;</h5><--->



 {% if request.user.is_authenticated %}
    <a href="{% url 'logout' %}"><button type="button" class="btn btn-outline-primary "> выход </button></a>
 {% else %}
    <a href="{% url 'login' %}"><button type="button" class="btn btn-outline-primary "> вход </button></a>
 {% endif %}
<button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
</div>
<div class="offcanvas-body" >
    <p><a href="{% url 'game_management:index' %}">Главная</a></p>
    {% if request.user.is_authenticated %}
    <p><a href="{% url 'game_management:schedule' %}">Расписание</a></p>
    <p><a href="{% url 'game_management:members' %}">Члены клуба</a></p>
    <p><a href="{% url 'game_management:masters' %}">Ведущие</a></p>
    <p><a href="{% url 'game_management:game_registered' %}">Записаны на игру</a></p>
    {% endif %}
    <p><a href="{% url 'game_management:results' %}">Результаты игр</a></p>
    <p><a href="{% url 'game_management:rating' %}">Рейтинг</a></p>
    <p><a href="{% url 'game_management:location' %}">Локации</a></p>
    {% if request.user.is_authenticated %}
    <p><a href="{% url 'game_management:promo' %}">Анонсы</a></p>
    <p><a href="{% url 'game_management:glossary' %}">Справочники</a></p>
    <p><a href="{% url 'game_management:bot' %}">Бот</a></p>
    <p>История</p>
    {% endif %}
</div>
</div>

<!-- MDB -->
<!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.js"></script><--->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>