game_management/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
#from game_management.views.tg_bot import bot_run

#bot_run()
app_name = 'game_management'

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/login/', auth_views.LoginView.as_view()),
    path('accounts/logout/', auth_views.LogoutView.as_view()),
    path('accounts/logout-then-login/', auth_views.logout_then_login),

    path('schedule', views.schedule, name='schedule'),
    path('schedule/schedule_update', views.schedule_update, name='schedule_update'),

    path('members', views.members, name='members'),
    path('masters', views.masters, name='masters'),
    path('game_registered', views.game_registered, name='game_registered'),

    path('results', views.results, name='results'),
    path('rating', views.rating, name='rating'),

    path('promo', views.promo, name='promo'),
    path('promo/update_promo', views.update_promo, name='update_promo'),
    path('promo/delete_promo', views.delete_promo, name='delete_promo'),

    path('glossary', views.glossary, name='glossary'),
    path('bot', views.bot, name='bot'),

    path('glossary/games', views.games, name='games'),
    path('glossary/games/update_game', views.update_game, name='update_game'),
    path('glossary/games/delete_game', views.delete_game, name='delete_game'),

    path('glossary/game_result', views.game_result, name='game_result'),
    path('glossary/game_result/update_result', views.update_result, name='update_result'),
    path('glossary/game_result/delete_result', views.delete_result, name='delete_result'),

    path('glossary/role', views.role, name='role'),
    path('glossary/role/update_role', views.update_role, name='update_role'),
    path('glossary/role/delete_role', views.delete_role, name='delete_role'),

    path('glossary/member_result', views.member_result, name='member_result'),
    path('glossary/member_result/update_member_result', views.update_member_result, name='update_member_result'),
    path('glossary/member_result/delete_member_result', views.delete_member_result, name='delete_member_result'),

    path('glossary/game_functions', views.game_functions, name='game_functions'),
    path('glossary/game_functions/update_function', views.update_function, name='update_function'),
    path('glossary/game_functions/delete_function', views.delete_function, name='delete_function'),

    path('location', views.location, name='location'),
    path('location/update_location', views.update_location, name='update_location'),
    path('location/delete_location', views.delete_location, name='delete_location'),
]

upsystems_bot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game_management/', include('game_management.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

game_management/views/bot.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth.decorators import login_required, permission_required
from game_management.views import tg_bot


@login_required()
def bot(request):
    context = {}
    return render(request, 'game_management/bot.html', context)

game_management/views/game_registered.py
import datetime
from datetime import timedelta

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from game_management.models import Member, RegisteredToGame, Schedule


@login_required()
def game_registered(request):
    today = datetime.date.today()
    schedule = Schedule.objects.filter(date__gte=today, date__lte=today + timedelta(days=6)).order_by('-date')
    registered_to_game = []
    for day in schedule:
        game = RegisteredToGame.objects.filter(schedule=day, active=True)
        number_registered = game.count()
        members = game.values_list('member__nickname', flat=True)
        registered_to_game.append([day, number_registered, members])
    context = {'registered_to_game': registered_to_game}
    return render(request, 'game_management/game_registered.html', context)

game_management/views/glossary.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth.decorators import login_required
from game_management.models import GameType, GameResult, Role, MemberResult, GameFunction, Location
from django.contrib.auth.models import User


@login_required()
def glossary(request):
    games = GameType.objects.filter(active=True).count()
    game_results = GameResult.objects.filter(active=True).count()
    roles = Role.objects.filter(active=True).count()
    member_results = MemberResult.objects.filter(active=True).count()
    game_functions = GameFunction.objects.filter(active=True).count()
    context = {'games': games, 'game_results': game_results, 'roles': roles, 'member_results': member_results,
               'game_functions': game_functions}
    return render(request, 'game_management/glossary.html', context)


@login_required()
def games(request):
    games = GameType.objects.filter(active=True)
    context = {'games': games}
    return render(request, 'game_management/glossary/games.html', context)


def update_game(request):
    name = request.POST['name']
    description = request.POST['description']
    try:
        game_id = request.POST['game_id']
        game = GameType.objects.get(id=game_id)
        game.game_name = name
    except:
        game = GameType(game_name=name)
    game.game_description = description
    game.save()
    return HttpResponseRedirect(reverse('game_management:games'))


def delete_game(request):
    try:
        game = GameType.objects.get(id=request.POST['to_delete'])
        game.active = False
        game.save()
    except:
        pass
    return HttpResponseRedirect(reverse('game_management:games'))


@login_required()
def game_result(request):
    results = GameResult.objects.filter(active=True)
    game_types = GameType.objects.all()
    context = {'results': results, 'game_types': game_types}
    return render(request, 'game_management/glossary/game_result.html', context)


def update_result(request):
    name = request.POST['result']
    game = GameType.objects.get(id=request.POST['game'])
    try:
        result_id = request.POST['result_id']
        result = GameResult.objects.get(id=result_id)
        result.game_result = name
    except:
        result = GameResult(game_result=name)
    result.game_type = game
    result.save()
    return HttpResponseRedirect(reverse('game_management:game_result'))


def delete_result(request):
    try:
        result = GameResult.objects.get(id=request.POST['to_delete'])
        result.active = False
        result.save()
    except:
        pass
    return HttpResponseRedirect(reverse('game_management:game_result'))

@login_required()
def role(request):
    roles = Role.objects.filter(active=True)
    game_types = GameType.objects.filter(active=True)
    context = {'roles': roles, 'game_types': game_types}
    return render(request, 'game_management/glossary/role.html', context)


def update_role(request):
    role_name = request.POST['role']
    description = request.POST['description']
    side = request.POST['side']
    game = GameType.objects.get(id=request.POST['game'])
    try:
        role_id = request.POST['role_id']
        role = Role.objects.get(id=role_id)
        role.role = role_name
    except:
        role = Role(role=role_name)
    role.role_description = description
    role.side = side
    role.game = game
    role.save()
    return HttpResponseRedirect(reverse('game_management:role'))


def delete_role(request):
    try:
        role = Role.objects.get(id=request.POST['to_delete'])
        role.active = False
        role.save()
    except:
        pass
    return HttpResponseRedirect(reverse('game_management:role'))


@login_required()
def member_result(request):
    results = MemberResult.objects.filter(active=True)
    context = {'results': results}
    return render(request, 'game_management/glossary/member_result.html', context)


def update_member_result(request):
    result = request.POST['name']
    result_type = request.POST['description']
    try:
        result_id = request.POST['game_id']
        member_result = MemberResult.objects.get(id=result_id)
        member_result.member_result = result
    except:
        member_result = MemberResult(member_result=result)
    member_result.member_result_type = result_type
    member_result.save()
    return HttpResponseRedirect(reverse('game_management:member_result'))


def delete_member_result(request):
    try:
        member_result = MemberResult.objects.get(id=request.POST['to_delete'])
        member_result.active = False
        member_result.save()
    except:
        pass
    return HttpResponseRedirect(reverse('game_management:member_result'))

@login_required()
def game_functions(request):
    game_function = GameFunction.objects.filter(active=True)
    context = {'game_function': game_function}
    return render(request, 'game_management/glossary/game_functions.html', context)


def update_function(request):
    name = request.POST['name']
    description = request.POST['description']
    try:
        game_id = request.POST['game_id']
        function = GameFunction.objects.get(id=game_id)
        function.game_function = name
    except:
        function = GameFunction(game_function=name)
    function.game_function_description = description
    function.save()
    return HttpResponseRedirect(reverse('game_management:game_functions'))


def delete_function(request):
    try:
        game = GameFunction.objects.get(id=request.POST['to_delete'])
        game.active = False
        game.save()
    except:
        pass
    return HttpResponseRedirect(reverse('game_management:game_functions'))


@login_required()
def location(request):
    locations = Location.objects.filter(active=True)
    user = User
    context = {'locations': locations, 'user': user}
    return render(request, 'game_management/glossary/location.html', context)

def update_location(request):
    loc_name = request.POST['name']
    loc_address = request.POST['address']
    loc_direction = request.POST['direction']
    loc_point = request.POST['point']
    try:
        loc_scheme = request.FILES['scheme']
    except:
        loc_scheme = None
    try:
        loc_photo = request.FILES['photo']
    except:
        loc_photo = None
    try:
        loc_id = request.POST['loc_id']
        loc = Location.objects.get(id=loc_id)
        loc.location_name = loc_name
    except:
        loc = Location(location_name=loc_name)
    loc.location_address = loc_address
    loc.location_directions = loc_direction
    loc.location_point = loc_point
    loc.location_photo = loc_photo
    loc.direction_photo = loc_scheme
    loc.save()
    return HttpResponseRedirect(reverse('game_management:location'))


def delete_location(request):
    try:
        location = Location.objects.get(id=request.POST['to_delete'])
        location.active = False
        location.save()
    except:
        pass
    return HttpResponseRedirect(reverse('game_management:location'))

game_management/views/location.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth.decorators import login_required
from game_management.models import GameType, GameResult, Role, MemberResult, GameFunction, Location
from django.contrib.auth.models import User

def location(request):
    locations = Location.objects.filter(active=True)
    context = {'locations': locations}
    return render(request, 'game_management/location.html', context)

def update_location(request):
    loc_name = request.POST['name']
    loc_address = request.POST['address']
    loc_direction = request.POST['direction']
    loc_point = request.POST['point']
    try:
        loc_scheme = request.FILES['scheme']
    except:
        loc_scheme = None
    try:
        loc_photo = request.FILES['photo']
    except:
        loc_photo = None
    try:
        loc_id = request.POST['loc_id']
        loc = Location.objects.get(id=loc_id)
        loc.location_name = loc_name
    except:
        loc = Location(location_name=loc_name)
    loc.location_address = loc_address
    loc.location_directions = loc_direction
    loc.location_point = loc_point
    loc.location_photo = loc_photo
    loc.direction_photo = loc_scheme
    loc.save()
    return HttpResponseRedirect(reverse('game_management:location'))


def delete_location(request):
    try:
        location = Location.objects.get(id=request.POST['to_delete'])
        location.active = False
        location.save()
    except:
        pass
    return HttpResponseRedirect(reverse('game_management:location'))

game_management/views/masters.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required


@login_required()
def masters(request):
    context = {}
    return render(request, 'game_management/masters.html', context)

game_management/views/members.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from game_management.models import Member


@login_required()
def members(request):
    members = Member.objects.all().order_by('registered_date')
    context = {'members': members}
    return render(request, 'game_management/members.html', context)

game_management/views/promo.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth.decorators import login_required, permission_required
from game_management.models import Promo


@login_required()
def promo(request):
    promo = Promo.objects.filter(active=True).order_by('-promo_date')
    context = {'promo': promo}
    return render(request, 'game_management/promo.html', context)


def update_promo(request):
    date = request.POST['date']
    par1 = request.POST['par1']
    text1 = request.POST['text1']
    par2 = request.POST['par2']
    text2 = request.POST['text2']
    par3 = request.POST['par3']
    text3 = request.POST['text3']
    par4 = request.POST['par4']
    text4 = request.POST['text4']
    promo_type = request.POST['promo_type']
    try:
        promo_id = request.POST['promo_id']
        promo = Promo.objects.get(id=promo_id)
        promo.promo_date = date
    except:
        promo = Promo(promo_date=date)
    promo.par1 = par1
    promo.text1 = text1
    promo.par2 = par2
    promo.text2 = text2
    promo.par3 = par3
    promo.text3 = text3
    promo.par4 = par4
    promo.text4 = text4
    promo.promo_type = promo_type
    promo.save()
    return HttpResponseRedirect(reverse('game_management:promo'))

def delete_promo(request):
    promo_id = request.POST['pr_id']
    promo = Promo.objects.get(id=promo_id)
    promo.active = False
    promo.save()
    return HttpResponseRedirect(reverse('game_management:promo'))

game_management/views/rating.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required


def rating(request):
    context = {}
    return render(request, 'game_management/rating.html', context)

game_management/views/results.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required


def results(request):
    context = {}
    return render(request, 'game_management/results.html', context)

game_management/views/schedule.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth.decorators import login_required
from game_management.models import Schedule, Location, GameType
import datetime
from datetime import date, timedelta
from django.core.paginator import Paginator


@login_required()
def schedule(request):
    date_now = datetime.date.today()
    schedule_cur = Schedule.objects.filter(active=True).order_by('-date', 'schedule_time_begin')
    games = GameType.objects.filter(active=True).order_by('game_name')
    location = Location.objects.filter(active=True).order_by('location_name')
    date_start = date.today() - timedelta(days=date.today().weekday())
    schedule_dic = {}
    schedule_last = {}
    for sch in schedule_cur:
        if sch.date >= date_start:
            if sch.date not in schedule_last:
                schedule_last[sch.date] = []
            schedule_last[sch.date].append(sch)
        else:
            if sch.date not in schedule_dic:
                schedule_dic[sch.date] = []
            schedule_dic[sch.date].append(sch)

    paginator = Paginator(list(schedule_dic.items()), 21)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    schedule = dict(page_obj.object_list)

    context = {'schedule_last': schedule_last, 'date_start': date_start, 'page_obj': page_obj, 'games': games,
               'location': location, 'schedule': schedule, 'date_now': date_now}
    return render(request, 'game_management/schedule.html', context)


def schedule_update(request):
    date = request.POST['date']
    begin = request.POST['time_begin']
    end = request.POST['time_end']
    loc_id = request.POST['location']
    game_id = request.POST['game']
    location = Location.objects.get(id=loc_id)
    game = GameType.objects.get(id=game_id)
    try:
        sch_id = request.POST['sch_id']
        schedule = Schedule.objects.get(id=sch_id)
        schedule.date = date
    except:
        schedule = Schedule(date=date)
    schedule.schedule_time_begin = begin
    schedule.schedule_time_end = end
    schedule.location = location
    schedule.game = game
    schedule.save()
    return HttpResponseRedirect(reverse('game_management:schedule'))

game_management/templates/game_management/glossary/game_functions.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Функции в игре</title>
<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
<!-- MDB -->
<!--<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.css" rel="stylesheet"/><--->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
<!-- Bootstrap core CSS -->
<link href="{% static 'game_management/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
<link href="{% static 'game_management/style.css' %}" rel="stylesheet" crossorigin="anonymous">
</head>
<body id="bg" style="background-image: url('{% static "img/back2.png"%}');">
<button type="button" onclick="window.close()" class="btn btn-outline-primary m-3"><i class="bi bi-x-lg"></i>&nbsp;Закрыть</button>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#funcModal">
  Добавить описание
</button>

<!-- Modal -->
<div class="modal fade" id="funcModal" tabindex="-1" aria-labelledby="funcModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="funcModalLabel">Добавить/Редактировать функцию</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action="{% url 'game_management:update_function' %}" method="post">
      {% csrf_token %}
      <div class="modal-body">
        <input type="number" class="form-control mb-2" name="game_id" id="game_id" readonly>
        <input type="text" class="form-control mb-2" name="name" id="name" placeholder="название">
        <input type="text" class="form-control mb-2" name="description"id="description" placeholder="описание">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="clearGameModal()">Закрыть</button>
        <button type="submit" class="btn btn-primary">Сохранить</button>
      </div>
      </form>
    </div>
  </div>
</div>

<table class="table table-sm table-hover m-3" style="max-width: 900px;">
    <thead>
    <tr class="table-primary">
        <th style="max-width: 200px;">Название</th>
        <th style="max-width: 600px;">Описание</th>
        <th style="max-width: 100px;"></th>
    </tr>
    </thead>
    <tbody>
    {% for game in game_function %}
    <tr onclick="fillGameModal(this);" data-bs-toggle="modal" data-bs-target="#funcModal" data-id="{{ game.id }}"
        data-name="{{ game.game_function }}" data-description="{{ game.game_function_description }}">
        <td>{{ game.game_function }}</td>
        <td>{{ game.game_function_description }}</td>
        <td class="text-end">
            <form action="{% url 'game_management:delete_function' %}" method="post">
                {% csrf_token %}
                <input type="number" value="{{ game.id }}" name="to_delete" hidden>
                <button type="submit" class="btn btn-sm btn-outline-danger">
                    <i class="bi bi-x-lg"></i>&nbsp;Удалить
                </button>
            </form>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>


<script src="{% static 'game_management/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'game_management/game_management.js' %}" crossorigin="anonymous"></script>

</body>
</html>

game_management/templates/game_management/glossary/game_result.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Результат игры</title>
<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
<!-- MDB -->
<!--<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.css" rel="stylesheet"/><--->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
<!-- Bootstrap core CSS -->
<link href="{% static 'game_management/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
<link href="{% static 'game_management/style.css' %}" rel="stylesheet" crossorigin="anonymous">
</head>
<body id="bg" style="background-image: url('{% static "img/back2.png"%}');">
<button type="button" onclick="window.close()" class="btn btn-outline-primary m-3"><i class="bi bi-x-lg"></i>&nbsp;Закрыть</button>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#resultModal">
  Добавить результат
</button>

<!-- Modal -->
<div class="modal fade" id="resultModal" tabindex="-1" aria-labelledby="resultModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="resultModalLabel">Добавить/Редактировать результат</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action="{% url 'game_management:update_result' %}" method="post">
      {% csrf_token %}
      <div class="modal-body">
        <input type="number" class="form-control mb-2" name="result_id" id="result_id" readonly>
        <input type="text" class="form-control mb-2" name="result" id="result" placeholder="результат">
        <select class="form-select mb-2"  name="game"id="game">
        {% for game in game_types %}
            <option value="{{ game.id }}">{{ game.game_name }}</option>
        {% endfor %}
        </select>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="clearResultModal()">Закрыть</button>
        <button type="submit" class="btn btn-primary">Сохранить</button>
      </div>
      </form>
    </div>
  </div>
</div>

<table class="table table-sm table-hover m-3" style="max-width: 800px;">
    <thead>
    <tr class="table-primary">
        <th style="max-width: 200px;">Победитель</th>
        <th style="max-width: 600px;">Игра</th>
        <th style="max-width: 100px;"></th>
    </tr>
    </thead>
    <tbody>
    {% for result in results %}
    <tr onclick="fillResultModal(this);" data-bs-toggle="modal" data-bs-target="#resultModal" data-id="{{ result.id }}"
        data-result="{{ result.game_result }}" data-game="{{ result.game_type.id }}">
        <td>{{ result.game_result }}</td>
        <td>{{ result.game_type.game_name }}</td>
        <td class="text-end">
            <form action="{% url 'game_management:delete_result' %}" method="post">
                {% csrf_token %}
                <input type="number" value="{{ result.id }}" name="to_delete" hidden>
                <button type="submit" class="btn btn-sm btn-outline-danger">
                    <i class="bi bi-x-lg"></i>&nbsp;Удалить
                </button>
            </form>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>



<script src="{% static 'game_management/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'game_management/game_management.js' %}" crossorigin="anonymous"></script>

</body>
</html>

game_management/templates/game_management/glossary/games.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Справочник игр</title>

<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
<!-- MDB -->
<!--<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.css" rel="stylesheet"/><--->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
<!-- Bootstrap core CSS -->
<link href="{% static 'game_management/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
<link href="{% static 'game_management/style.css' %}" rel="stylesheet" crossorigin="anonymous">

</head>
<body id="bg" style="background-image: url('{% static "img/back2.png"%}');">
<button type="button" onclick="window.close()" class="btn btn-outline-primary m-3"><i class="bi bi-x-lg"></i>&nbsp;Закрыть</button>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#gameModal">
  Добавить описание
</button>

<!-- Modal -->
<div class="modal fade" id="gameModal" tabindex="-1" aria-labelledby="gameModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="gameModalLabel">Добавить/Редактировать игру</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action="{% url 'game_management:update_game' %}" method="post">
      {% csrf_token %}
      <div class="modal-body">
        <input type="number" class="form-control mb-2" name="game_id" id="game_id" readonly>
        <input type="text" class="form-control mb-2" name="name" id="name" placeholder="название">
        <input type="text" class="form-control mb-2" name="description"id="description" placeholder="описание">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="clearGameModal()">Закрыть</button>
        <button type="submit" class="btn btn-primary">Сохранить</button>
      </div>
      </form>
    </div>
  </div>
</div>

<table class="table table-sm table-hover m-3" style="max-width: 900px;">
    <thead>
    <tr class="table-primary">
        <th style="max-width: 200px;">Название</th>
        <th style="max-width: 600px;">Описание</th>
        <th style="max-width: 100px;"></th>
    </tr>
    </thead>
    <tbody>
    {% for game in games %}
    <tr onclick="fillGameModal(this);" data-bs-toggle="modal" data-bs-target="#gameModal" data-id="{{ game.id }}"
        data-name="{{ game.game_name }}" data-description="{{ game.game_description }}">
        <td>{{ game.game_name }}</td>
        <td>{{ game.game_description }}</td>
        <td class="text-end">
            <form action="{% url 'game_management:delete_game' %}" method="post">
                {% csrf_token %}
                <input type="number" value="{{ game.id }}" name="to_delete" hidden>
                <button type="submit" class="btn btn-sm btn-outline-danger">
                    <i class="bi bi-x-lg"></i>&nbsp;Удалить
                </button>
            </form>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>


<script src="{% static 'game_management/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'game_management/game_management.js' %}" crossorigin="anonymous"></script>
</body>
</html>